/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Changelog: typeof import('./src/components/Changelog.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Clock: typeof import('./src/components/Clock.vue')['default']
    CurrentDay: typeof import('./src/components/CurrentDay.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LatestVersion: typeof import('./src/components/LatestVersion.vue')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SelectGateway: typeof import('./src/components/SelectGateway.vue')['default']
    SelectSession: typeof import('./src/components/SelectSession.vue')['default']
    SelectSiswa: typeof import('./src/components/SelectSiswa.vue')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
