/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Changelog: typeof import('./src/components/Changelog.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Clock: typeof import('./src/components/Clock.vue')['default']
    Column: typeof import('primevue/column')['default']
    copy: typeof import('./src/components/SelectPegawai copy.vue')['default']
    CurrentDay: typeof import('./src/components/CurrentDay.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LatestVersion: typeof import('./src/components/LatestVersion.vue')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SelectGateway: typeof import('./src/components/SelectGateway.vue')['default']
    SelectMeetingSession: typeof import('./src/components/SelectMeetingSession.vue')['default']
    SelectPegawai: typeof import('./src/components/SelectPegawai.vue')['default']
    SelectSession: typeof import('./src/components/SelectSession.vue')['default']
    SelectSiswa: typeof import('./src/components/SelectSiswa.vue')['default']
    SelectUser: typeof import('./src/components/SelectUser.vue')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
