/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    Button: typeof import('primevue/button')['default']
    Copyright: typeof import('./src/components/Copyright.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Divider: typeof import('primevue/divider')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
