/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppHeaderBack: typeof import('./src/components/AppHeaderBack.vue')['default']
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Camera: typeof import('./src/components/Camera.vue')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Copyright: typeof import('./src/components/Copyright.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    DrawerContent: typeof import('./src/components/DrawerContent.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Iconfield: typeof import('primevue/iconfield')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListTransaction: typeof import('./src/components/Transaction/ListTransaction.vue')['default']
    Loading: typeof import('./src/components/drawer/Loading.vue')['default']
    OpenCamera: typeof import('./src/components/drawer/OpenCamera.vue')['default']
    OpenQrcode: typeof import('./src/components/drawer/OpenQrcode.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TransferConfirmation: typeof import('./src/components/drawer/TransferConfirmation.vue')['default']
  }
  export interface ComponentCustomProperties {
    BadgeDirective: typeof import('primevue/badgedirective')['default']
  }
}
